/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3.1/userguide/building_java_projects.html
 */

plugins {
    kotlin("jvm") version "1.6.0"

    application
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    testCompileOnly("io.kotlintest:kotlintest-runner-junit5:3.1.9")
    implementation(kotlin("test"))
}

application {
    // Define the main class for the application.
    mainClass.set("SolutionKt")
}

sourceSets.main {
    java.srcDirs("common/", "years/y2021")
    resources {

    }
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(16))
    }
}

tasks.register<Copy>("copyInputsAndTests") {
    from(layout.projectDirectory.dir("years"))
    include("**/*.txt")
    into(layout.buildDirectory.dir("classes/kotlin/main/"))
}
