import org.jetbrains.gradle.ext.BeforeRunTask
import org.jetbrains.gradle.ext.GradleTask
import org.jetbrains.gradle.ext.runConfigurations
import org.jetbrains.gradle.ext.settings
import org.jetbrains.gradle.ext.Application as GradleApp;

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3.1/userguide/building_java_projects.html
 */

plugins {
    kotlin("jvm") version "1.9.21"
    id("org.jetbrains.gradle.plugin.idea-ext").version("1.1.7")

    application
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.10")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test:1.8.10")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit:1.8.10")

    testCompileOnly("io.kotlintest:kotlintest-runner-junit5:3.1.9")
    implementation("org.jetbrains.kotlin:kotlin-test:1.8.10")
}

application {
    // Define the main class for the application.
    mainClass.set("common.SolutionKt")
}

sourceSets.main {
    java.srcDirs("src/")
    resources {

    }
}

tasks.register<Copy>("copyInputsAndTests") {
    from("src/")
    include("**/*.txt")
    into(layout.buildDirectory.dir("classes/kotlin/main/"))
}

/*
idea.project.settings.runConfigurations {
    add(create(
        "Run Today",
        GradleApp::class.java
    ) {
        mainClass = "common.SolutionKt"
        programParameters = "today"
        beforeRun.add(GradleTask("copyInputsAndTests"))
    })
    add(create(
        "Run Test Today",
        GradleApp::class.java
    ) {
        mainClass = "common.SolutionKt"
        programParameters = "test today"
        beforeRun.add(GradleTask("copyInputsAndTests"))
    })
    add(create(
        "Run with Ask",
        GradleApp::class.java
    ) {
        mainClass = "common.SolutionKt"
        programParameters = "ask"
        beforeRun.add(GradleTask("copyInputsAndTests"))
    })
}*/
